### ISSUE TITLE
API - Pipe eventbrite results into display map

### ISSUE THREAD

**Issue by Jimmah661** [wesleyroach/FirstProject#10]
## User Story
As a user, I need to see the events in relation to my location

## Task
- [ ] Take EventBrite results
- [ ] Display Google Map
- [ ] Add event locations to the map

**Comment by Jimmah661** [comment]
linked to https://github.com/wesleyroach/FirstProject/issues/5
