### ISSUE TITLE
API - Eventbrite markers in Google Maps

### ISSUE THREAD

**Issue by frootloops64** [wesleyroach/FirstProject#28]
## User Story
As a user, I want to see the events near my location, so that I have something to click on to find out more information about it. 

## Tasks
- [ ] Get event coordinates from Evenbrite API.
- [ ] Create markers on map of those events.
- [ ] Show event details when marker is clicked.
