### ISSUE TITLE
HTML - Event Modal

### ISSUE THREAD

**Issue by frootloops64** [wesleyroach/FirstProject#9]
## User Story
As a user, I want to see more details of the selected event, so that I can buy tickets and create a MeetUp group or join an existing group. 

## Tasks
- [ ] Create Modal HTML code (and CSS styling if we have time)
- [ ] Button to purchase tickets for event
- [ ] Link to MeetUp website or modal
